=== HeroGamers/dis.gd/shortlink.schema.json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema#",
  "$id": "https://raw.githubusercontent.com/HeroGamers/dis.gd/json-validation/shortlink.schema.json",
  "title": "Shortlink",
  "description": "A dis.gd shortlink",
  "type": "object",
  "properties": {
    "link": {
      "description": "The main shortlink, without the 'dis.gd/' part",
      "type": "string"
    },
    "links": {
      "description": "Multiple other shortlinks that are linking to the same redirect",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "description": "The type of the shortlink",
      "type": "string",
      "pattern": "^Article|External Website|Website|Blogpost|Form|Server Invite|Store$"
    },
    "description": {
      "description": "The description of the shortlink",
      "type": [ "null", "string" ]
    },
    "redirect": {
      "description": "The true redirect of the shortlink",
      "type": "string"
    },
    "usefulness": {
      "description": "The usefulness for a given shortlink, rated between 1-5",
      "type": "integer",
      "minimum": 1,
      "maximum": 5
    }
  },
  "required": [ "link", "type", "description", "redirect" ,"usefulness" ]
}

=== HeroGamers/dis.gd/shortlinks.json
[
  {
    "link": "publicguidelines",
    "type": "Article",
    "description": "The Community Server Guidelines",
    "redirect": "https://support.discord.com/hc/en-us/articles/360035969312",
    "usefulness": 1
  },
  {
    "link": "gettingstartedonmobile",
    "type": "Article",
    "description": "How to get started with Discord - On mobile for beginners",
    "redirect": "https://support.discord.com/hc/articles/360046618751",
    "usefulness": 1
  },
  {
    "link": "howtoreport",
    "links": ["howtoreport", "serverid", "userid", "messageid"],
    "type": "Article",
    "description": "How to Properly Report Issues to Trust & Safety",
    "redirect": "https://support.discord.com/hc/articles/360000291932",
    "usefulness": 1
  },
  {
    "link": "beginnersguide",
    "type": "Article",
    "description": "How to use Discord - For beginners",
    "redirect": "https://support.discord.com/hc/articles/360045138571",
    "usefulness": 1
  },
  {
    "link": "contact",
    "links": ["contact", "support"],
    "type": "Form",
    "description": "Contact Support - Submit a request",
    "redirect": "https://support.discord.com/hc/requests/new",
    "usefulness": 1
  },
  {
    "link": "report",
    "links": ["request", "report"],
    "type": "Form",
    "description": "Contact Trust & Safety - Submit a request",
    "redirect": "https://support.discord.com/hc/en-us/requests/new?ticket_form_id=360000029731",
    "usefulness": 1
  },
  {
    "link": "safety",
    "type": "Website",
    "description": "Discord Safety Center",
    "redirect": "https://discord.com/safety",
    "usefulness": 1
  },
  {
    "link": "guidelines",
    "type": "Website",
    "description": "The Community Guidelines",
    "redirect": "https://discord.com/guidelines",
    "usefulness": 1
  },
  {
    "link": "tos",
    "links": ["tos", "terms"],
    "type": "Website",
    "description": "The Terms of Service",
    "redirect": "https://discord.com/terms",
    "usefulness": 1
  },
  {
    "link": "bugs",
    "links": ["bugs", "bughunting"],
    "type": "Article",
    "description": "How to Report Bugs",
    "redirect": "https://support.discord.com/hc/en-us/articles/360046057772",
    "usefulness": 2
  },
  {
    "link": "findmyid",
    "type": "Article",
    "description": "Where can I find my User/Server/Message ID?",
    "redirect": "https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-",
    "usefulness": 2
  },
  {
    "link": "discord101",
    "type": "Blogpost",
    "description": "How to use Discord for your classroom",
    "redirect": "https://medium.com/@discordnelly/how-to-use-discord-for-your-classroom-8587bf78e6c4",
    "usefulness": 2
  },
  {
    "link": "billing",
    "type": "Form",
    "description": "Contact Support about Billing issues - Submit a request",
    "redirect": "https://support.discord.com/hc/requests/new?ticket_form_id=360000118612",
    "usefulness": 2
  },
  {
    "link": "hypesquad",
    "type": "Website",
    "description": "Apply for HypeSquad - Do an application for HypeSquad Events",
    "redirect": "https://discord.com/hypesquad",
    "usefulness": 2
  },
  {
    "link": "moderation",
    "links": ["moderation", "modacademy", "dma103", "dma104", "dma201", "dma202", "dma203", "(and one for every other article)"],
    "type": "Website",
    "description": "Discord Moderator Academy (and links to all the resources)",
    "redirect": "https://discord.com/moderation",
    "usefulness": 2
  },
  {
    "link": "partners",
    "type": "Website",
    "description": "The Discord Partners page - Apply for Partner",
    "redirect": "https://discord.com/partners",
    "usefulness": 2
  },
  {
    "link": "feedback",
    "type": "Website",
    "description": "The Feedback Website",
    "redirect": "https://feedback.discord.com",
    "usefulness": 2
  },
  {
    "link": "bot-verification",
    "type": "Article",
    "description": "How to get a bot verified",
    "redirect": "https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting",
    "usefulness": 3
  },
  {
    "link": "2fa",
    "type": "Article",
    "description": "How to setup 2FA",
    "redirect": "https://support.discord.com/hc/en-us/articles/219576828-Setting-up-Two-Factor-Authentication",
    "usefulness": 3
  },
  {
    "link": "vfqual",
    "links": ["vfqual", "vsreqs"],
    "type": "Article",
    "description": "Server Verification Qualifications",
    "redirect": "https://support.discord.com/hc/en-us/articles/360001107231-What-Qualifies-for-Server-Verification-",
    "usefulness": 3
  },
  {
    "link": "partnercoc",
    "type": "Article",
    "description": "The Partnership Code of Conduct",
    "redirect": "https://support.discord.com/hc/articles/360024871991",
    "usefulness": 3
  },
  {
    "link": "dnsswap",
    "type": "Article",
    "description": "Troubleshooting: Changing your DNS provider as a troubleshooting step",
    "redirect": "https://support.discord.com/hc/en-us/articles/360034366151-Changing-Your-DNS-Provider",
    "usefulness": 3
  },
  {
    "link": "cprog",
    "type": "Form",
    "description": "Contact Support about Community Programs - Submit a request",
    "redirect": "https://support.discord.com/hc/requests/new?ticket_form_id=360000168511",
    "usefulness": 3
  },
  {
    "link": "lang-feedback",
    "type": "Form",
    "description": "Localization Improvement Form - Translation Issues",
    "redirect": "https://support.discord.com/hc/requests/new?ticket_form_id=360004944073",
    "usefulness": 3
  },
  {
    "link": "status",
    "type": "Website",
    "description": "Discord Operating Status",
    "redirect": "https://status.discord.com",
    "usefulness": 3
  },
  {
    "link": "nitro",
    "type": "Website",
    "description": "Showcase of Nitro benefits as well as buying Nitro",
    "redirect": "https://discord.com/nitro",
    "usefulness": 3
  },
  {
    "link": "vfs",
    "links": ["vfs", "verified"],
    "type": "Website",
    "description": "Verification (Verified Servers) - Apply for Verification",
    "redirect": "https://discord.com/verification",
    "usefulness": 3
  },
  {
    "link": "jobs",
    "type": "Website",
    "description": "Work for Discord - Jobs at Discord",
    "redirect": "https://discord.com/jobs",
    "usefulness": 3
  },
  {
    "link": "refund",
    "type": "Article",
    "description": "Discord's Refund Policy",
    "redirect": "https://support.discord.com/hc/en-us/articles/360012668071-Refund-Policy",
    "usefulness": 4
  },
  {
    "link": "googleplaystoreintegration",
    "type": "Article",
    "description": "How to buy Nitro on the Play Store",
    "redirect": "https://support.discord.com/hc/articles/360055386693",
    "usefulness": 4
  },
  {
    "link": "regionswap",
    "type": "Article",
    "description": "How to change the Voice Server Region",
    "redirect": "https://support.discord.com/hc/en-us/articles/216661717-How-do-I-change-my-Voice-Server-Region-",
    "usefulness": 4
  },
  {
    "link": "password",
    "type": "Article",
    "description": "How to Reset your Password",
    "redirect": "https://support.discord.com/hc/en-us/articles/218410947-I-forgot-my-Password-Where-can-I-set-a-new-one-",
    "usefulness": 4
  },
  {
    "link": "inbox",
    "type": "Article",
    "description": "How to use the in-app Inbox",
    "redirect": "https://support.discord.com/hc/articles/360045027712",
    "usefulness": 4
  },
  {
    "link": "macinstall",
    "type": "Article",
    "description": "macOS Installer Errors",
    "redirect": "https://support.discord.com/hc/en-us/articles/360022082931",
    "usefulness": 4
  },
  {
    "link": "mobilescreenshare",
    "type": "Article",
    "description": "Mobile Screenshare FAQ",
    "redirect": "https://support.discord.com/hc/articles/360058862134",
    "usefulness": 4
  },
  {
    "link": "credit",
    "type": "Article",
    "description": "Nitro Gifting - Account/Nitro Credit",
    "redirect": "https://support.discord.com/hc/en-us/articles/360030782312-Updates-to-Nitro-Gifting-Account-Credit-",
    "usefulness": 4
  },
  {
    "link": "boost",
    "links": ["boost", "serverboosting"],
    "type": "Article",
    "description": "Server Boosting",
    "redirect": "https://support.discord.com/hc/en-us/articles/360028038352-Server-Boosting-",
    "usefulness": 4
  },
  {
    "link": "servervideo",
    "type": "Article",
    "description": "Server Video Help Article",
    "redirect": "https://support.discord.com/hc/articles/360041721052",
    "usefulness": 4
  },
  {
    "link": "golivescreenshare",
    "type": "Article",
    "description": "Share your screen with Go Live - Screen Share",
    "redirect": "https://support.discord.com/hc/articles/360040816151",
    "usefulness": 4
  },
  {
    "link": "stagesfaq",
    "type": "Article",
    "description": "Stage Channels FAQ",
    "redirect": "https://support.discord.com/hc/articles/1500005513722",
    "usefulness": 4
  },
  {
    "link": "stickersfaq",
    "type": "Article",
    "description": "Stickers FAQ",
    "redirect": "https://support.discord.com/hc/articles/360056891113",
    "usefulness": 4
  },
  {
    "link": "voice_errors",
    "type": "Article",
    "description": "Troubleshooting: Voice connection errors",
    "redirect": "https://support.discord.com/hc/en-us/articles/115001310031-Voice-Connection-Errors",
    "usefulness": 4
  },
  {
    "link": "install",
    "links": ["install", "installfail"],
    "type": "Article",
    "description": "Windows Installer Errors",
    "redirect": "https://support.discord.com/hc/en-us/articles/209099387--Windows-Installer-Errors",
    "usefulness": 4
  },
  {
    "link": "gamepass",
    "type": "Article",
    "description": "Xbox Game Pass & Discord Nitro",
    "redirect": "https://support.discord.com/hc/en-us/articles/360035344491",
    "usefulness": 4
  },
  {
    "link": "testflight",
    "type": "External Website",
